name: Hourly IP Ping Check

on:
  schedule:
    - cron: '0 * * * *' # Esegue il controllo ogni ora (al minuto 0)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
          - name: Verifica Dominio MyFRITZ
            run: |
              MY_DOMAIN="IL_TUO_DOMINIO.myfritz.net" # Sostituisci con il tuo indirizzo MyFRITZ
              
              # Interroga il dominio MyFRITZ (segue i redirect e accetta SSL)
              if curl -m 10 -s -L -o /dev/null -w "%{http_code}" https://$MY_DOMAIN | grep -E "200|301|302|401|403"; then
                echo "Fritz!Box raggiungibile."
              else
                echo "ERRORE: Fritz!Box non raggiungibile!"
                exit 1
              fi
